CUModSquad/Camelot-Unchained

patcher/package.json

Some may find this helpful. Tested successfully in both Win10 and OSX.

Add 'setup' and 'setup:nix' npm run scripts.

---

patcher/src/sass/_chat.scss
patcher/src/ts/content/chat/ParseEmoji.tsx

Added CSE emoticons, changed regex, created case-sensitive and case-insensitive sections for commands, and added suggested abbreviations and variants to commands.

Add custom CSE emoticons

---

.gitignore
patcher/src/sass/_chat.scss
patcher/src/ts/content/chat/Room.tsx

I added the .vscode folder to the gitignore file. I would think that would already be there.
The main purpose of this pull request is to remove the gray chat room icons.
I deleted all code related to them. I personally don't believe in leaving dead code hanging around if I know about it.
From this:
to this:

Removed chat room icon and added .vscode directory to gitignore file

---

patcher/src/sass/_characterselect.scss
patcher/src/ts/sidebar/CharacterSelect.tsx

This removes the CSS for classes which can't currently be created. So, icons may appear blank if somebody still has one of those characters.
I pulled the list of icons from the character creation module.

Show gender-specific race icons in character select.

---

patcher/src/ts/sidebar/Sidebar.tsx

Get rid of the 30s login delays

Poll the channel state every half second

---

widgets/cu-xmpp-chat/src/components/ChatSession.tsx

Fixes an exception that is thrown after a system messages is displayed.
Tidies up the two connect functions, merges them into one internal connect function.

Fix chat system messages / tidy up connect code

---

game/hud/src/components/PlayerStatusComponent/components/Pills/index.scss
game/hud/src/components/PlayerStatusComponent/components/Pills/index.tsx
game/hud/src/components/PlayerStatusComponent/index.tsx
game/hud/src/lib/PlayerStatus.ts
game/hud/src/widgets/FriendlyTargetHealth/services/session/target.ts
game/hud/src/widgets/PlayerHealth/services/session/player.ts
game/hud/src/widgets/TargetHealth/services/session/target.ts

Adds wounds to PlayerStatusComponent / player Unit Frames

Add wounds

---

patcher/src/components/Hero/index.tsx
patcher/src/services/session/heroContent.ts

What this does:
1. Reverse sorting of videos, so the logo is the first index (0).
2. On load, show video with index 0 for 10 seconds.
3. After 10 seconds, switch to video with index 1 and start looping timer.
4. When reaching the end of the list of videos, start over at index 1 instead of 0.
This makes it so you see the awesome logo on first load but it doesn't get looped.

Sort hero videos by date

---

patcher/src/widgets/Sidebar/services/session/servers.ts

Handle null server, channel and character lists from API server in
apiServersToPatcherServers()
channelsToPatcherServers()
updateCharactersWithServers()

Handle null case when API server is misbehaving

---

patcher/src/widgets/Controller/components/ProgressBar/index.scss

Tweak the transition css so that the progress bar progresses smoothly rather than in 0.3s pulses.

Smooth progress bar

---

game/inventory/src/ts/components/inventory-window.tsx

Adds headers to item groups in inventory view, helps me find the item I want to equip easier.

Inv groups

---

library/package.json

Fix @types/lodash at version 4.14.56 for library

---

patcher/src/widgets/Controller/services/session/controller.ts

This fixes the Uncaught Type error messages about lastModified in console of the patcher.  See issue #107

Fix issue #107 Uncaught TypeError

---

.travis.yml
game/hud/package.json
game/hud/src/widgets/Building/components/BuildingApp/index.tsx
game/hud/src/widgets/Building/widgets/Actionbar/index.tsx
game/hud/src/widgets/Building/widgets/BuildPanel/widgets/DropLight/index.scss
game/hud/src/widgets/Building/widgets/common/InputOwnership.ts
game/hud/tsconfig.json
library/package-scripts.js
library/package.json
library/src/components/Flyout.tsx
library/src/core/client.ts
library/src/core/devClientInterface.ts
library/src/graphql/queries/MySocial.ts
library/src/graphql/queries/MyWarbands.ts
library/src/index.ts
library/src/signalR/index.ts
library/tsconfig.json
patcher/tsconfig.json

This is a test to see if the TravisCI build works.

Fix TravisCI build

---

patcher/src/widgets/CharacterCreation/services/session/attributeOffsets.ts
patcher/src/widgets/CharacterCreation/services/session/attributes.ts
patcher/src/widgets/CharacterCreation/services/session/factions.ts
patcher/src/widgets/CharacterCreation/services/session/races.ts

Remove use of :any that was used to avoid typing issues.  Use CSEError for error type and fix a couple of instances of referencing .message when it should be .Message
will fix #112

Avoid using :any and fix .Message

---

.travis.yml
game/hud/package-scripts.js
game/hud/package.json
game/hud/src/components/Announcement/__snapshots__/index.test.tsx.snap
game/hud/src/components/Announcement/index.test.tsx
game/hud/src/lib/reduxUtils.test.ts
library/package-scripts.js
library/package.json
library/src/util/objectUtils.test.ts

I have implemented some initial testing using [Jest](https://facebook.github.io/jest/).
This should allow us to test normal code along with react components themselves.
I have implemented the following:
- Add `jest` & dependencies to `game/hud` and `library` 
- Add `ts-jest` to allow TS code to be tested directly.
- Add `npm start test` command to `game/hud` and `library`
- Add `npm start test.watch` command to `game/hud` and `library`
- Update `.travis.yml` to trigger the test scripts
- Add initial sample test for `game/hud`
- Snapshot testing for `Announcement` component (does not do a great deal at the moment, is just to test the snapshot system. `game/hud/src/components/Announcement/index.test.tsx`
- Tests for the `clone` method on  `game/hud/src/lib/reduxUtils.ts`
- Tests for the …

Add jest testing

---

game/hud/package.json
game/hud/src/components/Announcement/__snapshots__/index.test.tsx.snap
game/hud/src/components/Announcement/index.test.tsx
game/hud/src/components/Compass/__snapshots__/index.test.tsx.snap
game/hud/src/components/Compass/index.test.tsx
game/hud/tslint.json
game/hud/typings.json
library/tslint.json
patcher/tslint.json

This PR adds some additional test examples using [enzyme](https://github.com/airbnb/enzyme)
It adds more in depth tests for:
- Announcement
- Compass
These tests use enzyme *Full DOM Rendering* and make use of [Jest timer mocks](https://facebook.github.io/jest/docs/en/timer-mocks.html)
---
**Announcement**
We test that the announcement component responds to `handlesAnnouncements` events.
We also ensure that messages are displayed correctly, and they disappear after a set time.
---
**Compass**
We test that the compass component renders different `client.facing` values.
We also ensure that compasses rendered at different facing values do not match each other.
---
Generally at least having some snapshot tests for each of the different states of these components will allow us to catch changes …

add enzyme testing and additional tests

---

game/hud/yarn.lock

There were still some port numbers in the yarn.lock file and prevented the dowload of the modules, so I removed them

Removed remaining port numbers

---

.travis.yml
library/package.json

This should hopefully fix #138 once library is republished and game/hud pulls latest version of library.

feature-travis-yarn - fixes #138

---

game/hud/src/widgets/Crafting/components/App.tsx
game/hud/src/widgets/Crafting/components/IngredientItem.tsx
game/hud/src/widgets/Crafting/components/Ingredients.tsx
game/hud/src/widgets/Crafting/components/JobDetails.tsx
game/hud/src/widgets/Crafting/components/PossibleIngredients.tsx
game/hud/src/widgets/Crafting/components/PossibleSlots.tsx
game/hud/src/widgets/Crafting/components/RecipeSelect.tsx
game/hud/src/widgets/Crafting/components/Tools.tsx
game/hud/src/widgets/Crafting/services/game/crafting/api.ts
game/hud/src/widgets/Crafting/services/game/crafting/queries.ts
game/hud/src/widgets/Crafting/services/game/crafting/queryText.ts
game/hud/src/widgets/Crafting/services/game/crafting/queryTypes.ts
game/hud/src/widgets/Crafting/services/session/job.ts
game/hud/src/widgets/Crafting/services/types/index.ts
game/hud/src/widgets/Crafting/styles/index.ts
game/hud/src/widgets/Crafting/styles/opts.ts

Add support for crafting slots.  Ingredients are now added to slots according to the recipe.

crafting slots

---

game/hud/src/widgets/Crafting/components/App.tsx
game/hud/src/widgets/Crafting/components/Tools.tsx
game/hud/src/widgets/Crafting/services/game/crafting/api.ts
game/hud/src/widgets/Crafting/services/game/crafting/errors.ts
game/hud/src/widgets/Crafting/services/game/crafting/queryText.ts

Fixed a couple of issues in the crafting UI
* item schema renamed name to debugname
* CraftingAPI response.data is now the raw json string, so use response.json() to get parsed version
* Improved some error messages

Update crafting UI to reflect back-end changes

---

patcher/src/widgets/CharacterCreation/services/session/character.ts
patcher/src/widgets/Controller/components/CharacterButton/components/CharacterInfo.tsx
patcher/src/widgets/Controller/components/CharacterButton/components/PlayerCounts.tsx
patcher/src/widgets/Controller/components/CharacterSelect/components/CharacterList.tsx
patcher/src/widgets/Controller/components/CharacterSelect/components/PlayerCounts.tsx

All issues from prior PR should be resolved. Rebased and fixed lint error.

Add PlayerCounts to character button and character select screen.

---

game/hud/src/components/HUDNav/components/HUDNavButton.tsx
game/hud/src/components/HealthBar/components/StatusIcon.tsx
game/hud/src/components/HealthBar/lib/healthFunctions.ts
game/hud/src/components/PassiveAlert.tsx
game/hud/src/components/ZoneName.tsx
game/hud/src/services/initialization/slashCommands/clientCommands.ts
game/hud/src/widgets/HUDFullScreen/HUDFullScreenView.tsx
game/hud/src/widgets/HUDFullScreen/components/Inventory/components/Containers/CraftingContainer.tsx
game/hud/src/widgets/HUDFullScreen/components/Inventory/components/InventorySlot.tsx
game/hud/src/widgets/HUDFullScreen/components/ItemShared/InventoryBase.tsx
game/hud/src/widgets/HUDFullScreen/components/PaperDoll/index.tsx
game/hud/src/widgets/HUDFullScreen/index.tsx

Fix some more lint errors

---

game/hud/src/widgets/Settings/panels/KeybindSettings.tsx

How did that one sneak through?

Fix lint error

---

game/hud/src/components/DevUI/index.tsx
game/hud/src/components/Watermark.tsx
game/hud/src/services/session/HUDZOrder.ts

This adds some very minor improvements to the devui.
- ensure maximize works
- tidy up close button

minor devui improvements

---

game/hud/src/components/Compass/POI/WarbandMembers.tsx

Fix missing key in warband member map markers

fix compass key bug

---

game/hud/src/widgets/HUDFullScreen/components/Map/index.tsx

This PR fixes issues with the map and leaking async reqeuests which occurs when `metadata.json` is not available for the given zone.
Now, when the metadata cannot be retrieved, the user is presented with a button to retry.
The query is also now only rendered when map metadata is present.

fix map issues when metadata is missing

---

package.json

`$ npm run build-all`
In the root folder will
* update library modules
* build library
* link library
* update game\hud modules
* link library into game\hud
* build game\hud
Designed to be used after pulling a bunch of changes, to make sure everything is up to date.

Global build-all commands

---

game/hud/src/components/SearchableList/index.tsx

this fixes a syntax error causing build to fail

fix syntax error

---

game/hud/src/lib/playerStateEqual.ts
game/hud/src/services/session/HUDZOrder.ts
game/hud/src/services/session/layout.ts
game/hud/src/services/session/layoutItems/ItemPlacementModeManager.ts
game/hud/src/widgets/HUDFullScreen/components/Inventory/components/ContextMenu/ContextMenuContent.tsx
game/hud/src/widgets/ItemPlacementModeManager/index.tsx
game/hud/yarn.lock
library/src/game/GameInterface.ts
library/src/game/constants/ItemPlacementTransformMode.ts
library/src/game/constants/index.ts
library/src/game/initGameInterface.ts
library/yarn.lock

I didn't do any styling cause can't really build project right now. Just added this in so we can get a starting point once we do get everything built.
We'll need to create some way for the UI to be told which TransformGizmoMode's to show. Any suggestions?

Add PlacementMode widget
