CUModSquad/Camelot-Unchained

patcher/src/sass/_news.scss

Both commits are me. I suck and didn't remember to replace the original css before pushing. 
Also had sent this to csegames/CU by mistake - closed that request and added it here.

Center pictures within the full-screen news articles

---

shared/widgets/CharacterCreation/components/AttributesSelect.tsx
shared/widgets/CharacterCreation/sass/_attribute-select.scss

Based on feedback from JB, this is my second shot at improving the look of the character attributes screen. The attribute titles are now on the same line as the attribute values and units are converted into more friendly formats.

Improve look of character attributes screen.

---

shared/widgets/CharacterCreation/sass/_attribute-select.scss

The attribute-row styles currently set padding-bottom: 10px; which leaves the text with no left margin and the contents vertically positioned at the top.  This also means the text for the attributes are outdented from the title.
This fix sets padding to 5px all round.  Content is centered vertically, and the text has a margin, and is now slightly indented from the title.

Fixes the padding around the attributes in attribute distribution

---

game/building/src/lib/SingleListener.ts
game/building/src/services/session/requester.ts
game/building/src/services/session/requester_fake.ts
game/building/src/widgets/BuildPanel/widgets/Blocks/components/MaterialAndShapePane/index.tsx
game/building/src/widgets/BuildPanel/widgets/Blocks/components/MaterialReplace/index.tsx
game/building/src/widgets/BuildPanel/widgets/Blocks/components/ShapesView/index.tsx
game/building/src/widgets/BuildPanel/widgets/Blocks/index.tsx
game/building/src/widgets/BuildPanel/widgets/Blocks/services/session/materials-replace.ts
game/building/src/widgets/BuildPanel/widgets/Blocks/services/session/materials.ts
game/building/src/widgets/BuildPanel/widgets/Blocks/services/session/reducer.ts
game/building/src/widgets/BuildPanel/widgets/Blocks/services/session/requester.ts
game/building/src/widgets/BuildPanel/widgets/Blocks/services/session/requester_fake.ts

There was an issue with listeners being registered and never unregistered. This eventually slowed down the ui till it was unusable.
The replace blocks tab lost it's state when switching to the block tab and back.

fixed some bugs with the building ui

---

library/src/restapi/RestAPI.ts

Blocking me from resuming work on the skillbar, error when trying to load abilities:
Failed to load resource: the server responded with a status of 403 (HTTPS Required) http://hatchery.camelotunchained.com:8000/api/craftedabilities?loginToken=....&characterID=jNIArqMwM24xNLL7AxT100
error: HTTPS Required | response: [object Object]

craftedabilities api requires https

---

game/hud/src/components/HUD/index.tsx
game/hud/src/index.tsx
game/hud/src/services/session/layout.ts

This change alters how the position (and size) of a HUD UI is persisted.  It is saved as a % or more accurately a fraction (between 0 and 1) representing the relative position and size in the window.  When restoring position (and size) the current window size is used, so that the UI element is restore to the same position at the new resolution.
However, I feel that this change on its own doesn't really solve any problems, the issues with it are:
1. if the window is resized, the UI elements are not adjusted and may now be off screen
2. scaling doesn't work well, at present this logic will adjust the pixel dimensions of the box for the UI, which creates its own set of issues with those UIs
3. the scroll wheel logic doesn't adjust the pixel dimensions, so a UI can't be expanded or shrunk …

Save and restore UI positions & size as %

---

game/hud/src/services/session/layout.ts

Each axis is treated separately.  If the point on the axis is closer to the start, it is saved anchored relative to the start.  If the point + width is closer to the end, the point is anchored relative to the end, otherwise the point is anchored relative to the center of the axis.
During a resize event, the anchored position is calculated based on the previous screen size, and used to calculate the new position at the new screen size.

Change repositioning logic to work based on anchored axes.

---

library/src/core/core.ts
library/src/core/utils/assert.ts
library/src/index.ts

Adds a DEBUG_ASSERT function to camelot-unchained library.
**Usage**
````javascript
import {DEBUG_ASSERT} from 'camelot-unchained';
export function doSomethingWithState(state: SomeState) {
DEBUG_ASSERT(state, 'state undefined in doSomethingWithState');
// now do something with it
}
```
````javascript
import {DEBUG_ASSERT} from 'camelot-unchained';
render() {
const widget: any = this.props.widget[this.props.name];
DEBUG_ASSERT(widget, 'widget ' + this.props.name + ' is undefined in SomeComponent:render()');
// rest assured, widget is now defined
}
```
Use DEBUG_ASSERT to ensure that a variable or parameter is what you would expect it any given point.  Use of DEBUG_ASSERT will help find bugs more quickly and closer to where they happen making it easier to track down the cause.
They can also …

DEBUG_ASSERT

---

game/hud/src/components/HUD/index.tsx
game/hud/src/services/session/layout.ts

Fixes the case where minimising the client window causes UIs to be sized to 1x1 pixels.
Also, removes some obsolete positioning code.

Fix positioning when minimised & cleanup obsolete code

---

game/building/src/lib/BuildingItem.ts
game/building/src/widgets/BuildPanel/widgets/Blocks/components/MaterialAndShapePane/index.tsx
game/building/src/widgets/BuildPanel/widgets/Blueprints/components/BlueprintsPane/index.tsx
game/building/src/widgets/BuildPanel/widgets/DropLight/components/DroplightPane/index.tsx
game/building/src/widgets/BuildPanel/widgets/DropLight/components/LightSelector/index.tsx
game/building/src/widgets/BuildPanel/widgets/RecentSelections/components/RecentSelections.tsx
game/building/src/widgets/BuildPanel/widgets/RecentSelections/index.scss

Droplights now show up in the recently used pane again.
Blueprints will not have broken images when displayed in the recently used pane.
The recently used pane now works off materials instead of blocks, usability suggestion from Necromaniak.

bug fixes and improvements to the recently used pane

---

game/hud/src/components/HUD/index.tsx
game/hud/src/services/session/layout.ts

There was an issue with positioning of scaled widgets, particularly noticeable with widgets scaled below 1.0 but the same issue exists for widgets scaled above 1.0.  It seems that (don't know if this intentional or not) the div for the widget is scaled around the center point, so the left and right top and bottom edges all move inwards.
This means that if we shrink a widget below 1.0, and then move that widget to butt up against the screen edge, the co-ordinates of that widget now overlap the edge of the screen.  The forceOnScreen() logic comes along and moves it back on screen, which means the widget now has a gap between it and the screen edge.
The fix is to calculate the screen margin (the amount of pixels a UI is allowed to overlap the edge of the screen) based on the current widgets …

Fix positioning scaled widgets

---

game/hud/src/components/HUD/index.tsx
game/hud/src/services/session/layout.ts

1. Fixes the issue where resizing re-evaluated a widgets anchor point.  Now, the anchor point is only ever evaluated when a widget has just been dragged (ie in SAVE_POSITION)
2. Fixes an issue where widget positions were not being persisted correctly (specifically, they were not being loaded correctly, always being overridden by the default positions).

Fixed positioning on resize, also fix loading saved position

---

game/hud/src/services/session/layout.ts

If a new widget is added to HUD it will now be correctly added when loading saved state.  Similarly if a widget is removed from HUD, it is dropped from saved state.  Only if a widget is current and appears in saved state will its position be restored.

Handle missing and obsolete widgets during load

---

patcher/src/ts/redux/modules/channels.ts
patcher/src/ts/sidebar/PatchButton.tsx
patcher/src/ts/sidebar/ServerSelect.tsx

A "bunch of bullshit" to get around users having to select a character (that already appears to be selected) to get the play button to light up. The store need to be consolidated (working on that) currently its race condition/synchronization hell. I should be able to flush this code once the store gets sorted out. But I figured a few kludges are worth it now, been seeing login issues/complaints on the forums.
Note: it still has the 30's delay lameness, What is the cost of making this call(patcherAPI.ts line 118):
public getAllChannels() : Channel[] {
if (this._api.channelData) {
return Array.prototype.slice.call(this._api.channelData).sort(function(a:Channel, b:Channel) {
return this.getChannelValue(a) - this.getChannelValue(b);
}.bind(this));
}
return [];
}
Does that result in a web …

Work around initial login char select issues

---

game/hud/src/services/session/layout.ts

In loadState there was a test for state.reset without first ensuring state was not null, which it is when dealing with empty local storage.

Fixes an issue where HUD does not load if localstorage is empty

---

game/hud/src/services/session/layout.ts

Loading state currently just calls JSON.parse() but that will throw an exception if the JSON is invalid.  This change adds a wrapper to that call, that will return null if the settings are corrupt which will lead to default settings being loaded.  Details of the error are written to the console including the corrupt JSON string.

Add resilience when loading hud state

---

patcher/src/components/QuickSelect/index.scss

Change cursor for QuickSelect activeView to a pointer, to indicate that it can be used to open the list.  It also prevents the text cursor appearing when moving over the text.

Change cursor for QuickSelect activeView to a pointer.

---

patcher/src/components/QuickSelect/index.tsx
patcher/src/widgets/Controller/components/CharacterSelect/index.scss
patcher/src/widgets/Controller/components/CharacterSelect/index.tsx
patcher/src/widgets/Controller/components/GameSelect/index.scss
patcher/src/widgets/Controller/components/GameSelect/index.tsx
patcher/src/widgets/Controller/components/ServerSelect/index.scss
patcher/src/widgets/Controller/components/ServerSelect/index.tsx

This is not a complete fix, there are two main issues with it:
* The itemHeight is hard coded
* There is some kind of delay when no longer needing scroll bars before UI properly updates.  This can be seen if you have 7 characters and delete one, then immediately open up the character list, there is space left for a scroll bar, that disappears after a few seconds.
The change adds itemHeight={n} property to QuickSelect, which QuickSelect uses to predict if a scroll bar will be required to display the supplied number of items.  If no scroll bar is required, overflow: hidden is added to the popup.  This prevents the scrollbar appearing while the popup list is transitioning into view if the resulting list will not show a scrollbar.  Giving a much nicer animation. …

Don't display scroll bar for quick select items that don't need them

---

game/hud/src/components/PlayerStatusComponent/components/Pills/index.tsx

React is complaining about the use of ```-webkit-clip-path``` as a style property name and suggested using ```WebkitClipPath``` instead, so I have!

Use WebkitClipPath rather than -webkit-clip-path for style property

---

patcher/src/components/App/index.tsx
patcher/src/components/OverlayView/index.tsx
patcher/src/widgets/Controller/components/ControllerDisplay/index.tsx

Removes console error about defining `componentDidUnmount` instead of `componentWillUnmount`.  
It's never called anyway as far as I can tell, ie the component is never unmounted so the code is a bit redundant but at least it's now correct and redundant.

It's componentWillUnmount not componentDidUnmount

---

game/hud/package.json
game/hud/src/widgets/Social/components/GridViewPager.tsx
game/hud/src/widgets/Social/components/OrderContent.tsx
game/hud/src/widgets/Social/components/OrdersGrid.tsx
game/hud/src/widgets/Social/components/OrdersList.tsx
game/hud/src/widgets/Social/components/SocialMain.tsx
game/hud/src/widgets/Social/services/session/nav/testNav.tsx
library/package.json
library/src/components/GridView.tsx
library/src/util/compare.ts
library/src/util/index.ts

Notes:
1. Column sorting on `GridView` has been changed to support only a single column.  This is because the multi-column sorting logic wasn't working, and would be complicated to make it work, so for now, we will go with single column sorting.
2. Column sorting has now been added to the Orders listing.
3. A subtle behaviour of `GridViewPager` that isn't obvious but is important to make it work deserves a bit of explanation.  Using `GridViewPager` we only ever supply a single page of data to the underlying `GridViewImpl`, yet we have page numbers and a pager UI.  How does GridView know to ignore the page number when working out what index to display data from?
Well, in fact it doesn't.  It still does `startIndex = this.state.page * this.props.itemsPerPage` but when using `GridViewPager` …

Cu order browser

---

library/src/util/apisaucelite.ts
library/src/webAPI/controllers/Characters.ts
library/src/webAPI/controllers/Content.ts
library/src/webAPI/controllers/GameData.ts
library/src/webAPI/controllers/Groups.ts
library/src/webAPI/controllers/Orders.ts
library/src/webAPI/controllers/Plots.ts
library/src/webAPI/controllers/Presence.ts
library/src/webAPI/controllers/ServerListHelper.ts
library/src/webAPI/controllers/Traits.ts
library/src/webAPI/controllers/Warbands.ts

This change detects a JSON response from the api server and returns the parsed JSON response in `response.error` or if a non-JSON response it returns a `response.error` object with Code and Message fields filled.
So in all cases, can do
```
if (response.error) {
const { Code, Message } = response.error;
}
```
Where the API has returned a JSON response, the error object may also contain a ```FieldCodes``` array whose contents will include a `Code` and a `Message` and potentially other data depending on the main error code (`response.error.Code`).
Error types are defined by 'camelot-unchained/webAPI/apierrors'
Additional Notes:
`response.error` is only defined if there was an error and `response.ok` will also be `false`

Return parsed CSE Error object

---

library/src/util/apisaucelite.ts

Checks for a response and response headers before attempting to parse response as JSON to avoid throwing an exception under certain network conditions.  Fixes #102

Handle missing response when parsing errors

---

patcher/src/components/Sound/index.tsx
patcher/src/widgets/Controller/components/PatchButton/index.tsx

This PR addresses the following issues:
1. Pause music while client is running
2. The background music is supposed to play in a loop and wasn't
3. Fades music in/out instead of abruptly pausing playing.
Notes:-
Added an ability to pause music playing by firing a pause-music event with true/false argument, which the sound component pickups up and sets paused state.  The existing logic that pauses/resumes video now also pauses/resumes music.
The background audio was not looping properly.  It would play once, then seeming randomly start playing again, in fact it would start playing again whenever a UI sound was triggered.
When sound is paused/resumed, it is now fades out/in which sounds better.  There is a quirk in that I wanted mute/unmute to be abrupt (not fade) and mute is abrupt but …

Pause music while client is running

---

patcher/src/widgets/CharacterCreation/index.tsx
patcher/src/widgets/CharacterCreation/services/session/attributeOffsets.ts
patcher/src/widgets/CharacterCreation/services/session/attributes.ts
patcher/src/widgets/CharacterCreation/services/session/factions.ts
patcher/src/widgets/CharacterCreation/services/session/races.ts

Switch to use ``webAPI.GameDataAPI.getAttributeOffsetsV1`` to fetch attribute offsets.
Notes:
``apiHost`` and ``apiVersion`` parameters were dropped with apiHost being determined by ``GameDataAPI`` and version determined by function name (ie hard coded).  Hope this is ok.
Also, the typings on GameDataAPI calls are a bit naff, to the point that because of ts-lint was forced to add :any to the value param to stop lint complaining.  Would be nice to have a named type definition for these generated APIs that we can use for the value type.
Also, I can expand this PR by converting some of the other APIs to use ``GameDataAPI`` if you want (or submit them as separate PRs).

Fix attribute offsets

---

patcher/package.json

This was causing errors in the TravisCI build.

Update @types/react-addons-transition-group version

---

library/src/util/apisaucelite.ts

error.response may be undefined for old error message formats.
Note, we fixed this before #103 but something ate it.

Handle missing error response

---

.travis.yml
game/hud/package.json
game/kos/package.json
game/perfhud/package.json
library/package.json
library/src/components/GridView.tsx
widgets/cu-character-creation/package.json
widgets/cu-xmpp-chat/package.json

Changes:
- node version is now set to `7` instead of `6`.
- `npm install` commands have separated and moved to the `before_install` section
- builds and tests have been organized to separate lines
- made use of `$TRAVIS_BUILD_DIR` environment variable to simplify `cd` calls.
These changes result in a much nicer and more meaningful output from travis. e.g. https://travis-ci.org/CUModSquad/Camelot-Unchained/builds/236572039
There was a lint issue introduced in https://github.com/CUModSquad/Camelot-Unchained/commit/9142e7759e561cca51fa7c417e2d8b4fbb790bdc which is now fixed.
The existing `postinstall` scripts are run even when the modules are installed into the `node_modules` directory e.g. `rimraf typings && typings install` will run on `node_modules/camelot-unchained` whilst running `npm …

update travis config, postinstall scripts and lint errors

---

widgets/cu-xmpp-chat/package.json
widgets/cu-xmpp-chat/src/components/JoinRoomList.tsx

The `cu-xmpp-chat` library was using an old version of `camelot-unchained` this updates the version to latest and fixes minor upgrade issues for tsc build.
If these changes are ok, would it also be possible to get `cu-xmpp-chat` published to the registry.

update cu-xmpp-chat to use latest library

---

game/hud/package.json
library/package.json
widgets/cu-character-creation/package.json
widgets/cu-xmpp-chat/package.json

I have been attempting to get `yarn` to work on travis and have identified a couple of issues:
1. we need `rimraf` installed as a devDependency for the projects which need it.
2. the previous postinstall script I added `cwd-in-node-modules || rimraf typings && typings install` is incorrect and should actually be `cwd-in-node-modules || (rimraf typings && typings install)` .
These are happening because travis is running on a non windows setup, and `sh` is interpreting the scripts slightly different.
If these changes are ok, would it be possible to publish:
- `camelot-unchained`
- `cu-xmpp-chat`
(sorry for all the re-publishing)

fix scripts and devDependencies

---

widgets/cu-xmpp-chat/package.json
widgets/cu-xmpp-chat/yarn.lock

This upgrades library for `cu-xmpp-chat` to latest version.
This will solve some of the final travis build issues we are having (pending a PR to upgrade library and cu-xmpp-chat on game/hud).
Seems to build nicely locally, not 100% sure if it is still functional though (not sure what to test)
I will submit a PR to upgrade libraries on game/hud (and test out travis build) once this is published to the registry.

upgrade library for cu-xmpp-chat

---

library/src/components/GridView.tsx

Currently you have to define a search function for each column of a grid. There are several reasons for it.
1. You need to tell the sort function, which column you want to use for sorting
2. You have to be careful, if you are sorting numbers. Standard behaviour is to turn numbers into strings, if no sort function is available for .sort, which means a wrong order
3. You need to do something special, like sorting this column using another column.
There is a solution for 1 and 2. If you use the function in the key of the columnDefinition on a row of data, it returns the value of the column for this row. This is either a string or a number. They are compared directly with each other with "<".  This comparison is working correctly for strings and numbers.
In most cases the key-function returns …

Improve sorting in GridView

---

.gitignore
Camelot Unchained.code-workspace

This PR ignores **/*.code-workspace except for one shared workspace called Camelot Unchained.
Custom workspaces can be created and called anything you like, for example, my.code-workspace that has your own preferred set of root folders.
Descendent folders can be root folders, so it's great for pulling out the thing you are currently working on making it quick to find.
For more information see: https://code.visualstudio.com/docs/editor/multi-root-workspaces

Support VSC .code-workspace - multi-root workspaces

---

game/hud/src/widgets/Building/widgets/BuildPanel/components/BuildPanel/index.tsx

the function materialSelectorDeactivated is called each time the material selector should hide. Because of that showMaterialSelector has to bet set to false.

bugfix: properly deactivate the material selector 

---

patcher/src/components/WindowHeader/index.scss

Changed the position of the sound and fx icons, so that they are visible everywhere on the patcher (e.g. character creation).

Sound & FX icon position

---

patcher/src/widgets/Controller/components/Login/index.tsx

Currently when checking remember me, form is not reset. This will reset the form.

Reset form inputs upon unchecking remember me

---

game/hud/src/components/InteractiveAlert/ProgressionAlert.tsx
game/hud/src/components/InteractiveAlert/TradeAlert.tsx
game/hud/src/components/InteractiveAlert/index.tsx
game/hud/src/components/Progression/RewardsView.tsx
game/hud/src/components/Progression/index.tsx
game/hud/src/services/actions/trade.ts
game/hud/src/widgets/Crafting/services/game/crafting/queryTypes.ts
game/hud/src/widgets/Crafting/services/session/job.ts
game/hud/src/widgets/Crafting/services/session/recipes.ts
game/hud/src/widgets/HUDFullScreen/components/Inventory/components/InventoryBody.tsx
game/hud/src/widgets/HUDFullScreen/components/Inventory/index.tsx
game/hud/src/widgets/HUDFullScreen/components/ItemShared/InventoryBase.tsx
game/hud/src/widgets/HUDFullScreen/components/TradeWindow/components/TradeDropContainer.tsx
game/hud/src/widgets/HUDFullScreen/components/TradeWindow/components/TradeWindowMidSection.tsx
game/hud/src/widgets/HUDFullScreen/components/TradeWindow/components/TradeWindowView.tsx
game/hud/src/widgets/HUDFullScreen/components/TradeWindow/index.tsx
game/hud/tslint.json

Since lint has been broken, a bunch of lint errors have crept in.  This PR addresses those and also (temporarily) disables the "check-separator" rule which is what is currently crashing lint.  Once there is a fix for tslint, we should ofc re-enable this option.

Fix a bunch of lint errors

---

game/hud/package-scripts.js

Fixes an issue that causes the build to fail whenever the hatchery api server is down on windows 8.1
|| true doesn't work on win 8.1
|| echo continue... does though, and should work on win10 also

Allow builds to continue on win 8.1 as well

---

patcher/src/services/patcher/index.ts
patcher/src/widgets/Controller/components/ControllerDisplay/components/ControllerDisplayView.tsx
patcher/src/widgets/Controller/components/ControllerDisplay/index.tsx
patcher/src/widgets/Controller/components/FatalError/index.tsx
patcher/src/widgets/Controller/components/PatcherError/index.tsx
patcher/src/widgets/Controller/services/session/controller.ts

Normal errors are displayed in an orange bar at the bottom of the screen.  If there is more than one error the first is displayed and an indicator of how many other errors exist.  Clicking the bar clears that error, showing the next error if there is one.
If the error is fatal, a fatal error dialog is shown that prevents further use of the patcher with a message asking the user to restart the patcher.  If other errors were received before the fatal error, they are also displayed in the dialog.

Add Error and Fatal error alerts.

---

game/hud/src/components/HealthBar/components/HealthBarViewCompact.tsx
game/hud/src/components/HealthBar/components/HealthBarViewFull.tsx
game/hud/src/components/HealthBar/components/HealthSlideOut.tsx
game/hud/src/components/HealthBar/lib/healthFunctions.ts

If you have any suggestions, improvements, or additional functionality you'd like added just let me know and I will be happy to make the changes.
changes made:
- added `mouseOver` property to state
- added functions to handle `onMouseOver` and `onMouseLeave`
- added `HealthSlideOut` component
- added `mouseOver` state
- added functions to handle `onMouseOver` and `onMouseLeave`
- added `HealthSlideOut` component
- added `getBodyPartsCurrentHealth()` function to return array of all body parts health
- added transition: right for animations
- added `valueOpacity` and transition: opacity to HP values to cause make them 'fade-in' on mouse-over
- adjusted `marginLeft` on middle two `ValueContainer` to fix numbers touching the right border

added HealthSlideOut and helper functions to compact and full health bars

---

game/hud/aliasify.config.js
game/hud/package.json
game/hud/src/widgets/Settings/SettingsMain.tsx
game/hud/src/widgets/Settings/components/Key.tsx
game/hud/src/widgets/Settings/components/KeyBind.tsx
game/hud/src/widgets/Settings/components/SettingsPanel.tsx
game/hud/src/widgets/Settings/components/settingsRenderer.tsx
game/hud/src/widgets/Settings/panels/AudioSettings.tsx
game/hud/src/widgets/Settings/panels/GraphicSettings.tsx
game/hud/src/widgets/Settings/panels/InputSettings.tsx
game/hud/src/widgets/Settings/panels/KeybindSettings.tsx
game/hud/src/widgets/Settings/tabs/Addon.tsx
game/hud/src/widgets/Settings/tabs/General.tsx
game/hud/src/widgets/Settings/tabs/Interface.tsx
game/hud/src/widgets/Settings/tabs/buttons.ts
game/hud/src/widgets/Settings/utils/configVars.ts
game/hud/tsconfig.json
game/hud/yarn.lock

*Different parts of the build tools use different terminology for these, but I will call them import paths because that's the TypeScript name for them.*
This PR adds support for import paths.  Import paths are a way to avoid having to use long relative paths in your imports for things that are commonly imported and meant to be shared.
```import { something } from '../../../../../components/something';```
becomes
```import { something } from 'components/something';```
I have setup support for the following import paths:
**components**
**widgets**
**services**
**lib**
**UI**
The first 4 correspond to the main source directories under `src/` and is enabled by the "baseUrl": typescript setting and `UI` maps to `components/UI`.
```import { TabbedDialog } from 'UI/TabbedDialog';```
The …

Add support for import paths 

---

patcher/src/widgets/Controller/components/CharacterSelect/components/CharacterSelectList.tsx

This first sorts servers by server.available, then sorts by selectedServer. Results in 'online' servers being at the top of the list.

Show available servers first on charselect.

---

library/src/components/Chat/components/ChatLineParser.tsx
library/src/components/Chat/components/ParseNicks.tsx

Since the room member lists were disabled in chat, the nick parser has been triggering the brain fried core dumped warning because the RE generated started matching an empty string.
This PR recognises when there aren't any nicks to parse, and returns undefined, so when building up the parser tokens list we can chose to not add the nick parser.

Fix brain fried core dumped

---

game/hud/src/components/Watermark.tsx

This moves the watermark to a spot that's less likely to cover windows (mainly alert dialogs) and increases the z-index, so it is on top of the full-screen UI widgets.

Move watermark above zone name widget and increase z-index.

---

game/hud/src/components/ContextMenu.tsx
game/hud/src/services/actions/contextMenu.ts

This PR goes part way to solving the right click context menu issues described in #200 
It does the following:
1. don't display the context menu if there are no options.  This means that if you happen to right click your own portrait and you are not in a warband you won't get a context menu so it wont steal further right clicks (though it still steals the initial one).
2. if the context menu is open, left or right clicking anywhere but on an option will close it.  This still means that the click to close the menu is stolen from the client, so still steals two right clicks requiring a third to turn.
Also fixed z-order of the menu so the options are not behind the unit frame.
This is not a complete solution to the problem described in #200

Improve Context Menu behaviour #200

---

patcher/src/widgets/Controller/components/CharacterButton/components/CharacterInfo.tsx
patcher/src/widgets/Controller/components/CharacterButton/components/GameSelect.tsx

The only thing I wasn't able to fix about this was the <HoverArea /> hack, which I think might require a greater re-work. More of the black area is hoverable on GameSelect now though, so it functions a little better... just not in the HoverArea still. If there's anything else I can fix up on this PR, just let me know and I'll be happy to work on it.
changes made: 
- render `<IdleShine>` conditionally
- add `updateAnimation()` function and call on mouse over to reset state to trigger re-render of `<IdleShine>` so it will never play at the same time as the active shine
- add `handleMouseOver()` wrapper function to support multiple callbacks on the onMouseEnter listener
- rename `imageShine` to `idleShine` to match the shine from the CharacterSelect widget for consistency
- add on-hover …

clean up animations on the CharacterSelect and GameSelect widgets

---

game/hud/src/widgets/Crafting/components/App.tsx
game/hud/src/widgets/Crafting/components/Button.tsx
game/hud/src/widgets/Crafting/components/Ingredients.tsx
game/hud/src/widgets/Crafting/components/Input.tsx
game/hud/src/widgets/Crafting/styles/index.ts

The main purpose of this PR is to fix an issue with input ownership if selecting the text of a quantity or quality field rather than clicking in it.  This is an annoyance for crafters and even a quit point for one.  https://forums.camelotunchained.com/topic/1184-crafting-ui-click-throughkeypress-issue/
Other fixes included in this PR are:
* Fixed font size for +/- buttons
* Make disabled buttons look and behave disabled.
* Make disabled ingredient quantity look disabled.
* Fix issue with changing quantity and clicking add too quickly
Removed `onchange` timeout from `Input` component and instead debounce the `setQuantity` and `setQuality` methods.  The timeout onChange was attempting to reduce the number of api calls made when changing quantity or quality, but it was also causing problems, …

Fix crafting input ownership + awesomeness

---

game/hud/webpack.config.js

This is a minor change to swap the webpack sourcemap type.
The current `eval-source-map` should work nicely in the browser for development, but does not work when in the client. I have swapped this to `source-map` to give solid support wherever the code is running.
This should make the `yarn start dev.webpack.hatchery` easier to debug with full source maps.

Minor change to webpack sourcemap type

---

game/hud/src/widgets/HUDFullScreen/components/Inventory/components/ContextMenu/ContextMenuAction.tsx

There is an issue with the Inventory action menu cool down timer logic that results in the following warnings being issued by react
```Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.```
This PR fixes that issue by not clobbering cooldownTimeout as soon as it's set.

Fix clearing cooldown timer on action menu

---

game/hud/src/components/HealthBar/components/HealthBarViewMini.tsx

This PR fixes an issue where react was throwing an error complaining that you cannot extend `PureComponent` and implement `shouldComponentUpdate` at the same time.

fix HealthBarViewMini

---

library/src/components/TabPanel.tsx

This fixes issues where tab dividers did not have keys causing react to throw loads of errors regarding unique keys.

fix tab panel keys

---

game/hud/src/widgets/Crafting/components/App.tsx
game/hud/src/widgets/Crafting/components/Button.tsx
game/hud/src/widgets/Crafting/components/Close.tsx
game/hud/src/widgets/Crafting/components/IngredientItem.tsx
game/hud/src/widgets/Crafting/components/Ingredients.tsx
game/hud/src/widgets/Crafting/components/Input.tsx
game/hud/src/widgets/Crafting/components/JobDetails.tsx
game/hud/src/widgets/Crafting/components/JobType.tsx
game/hud/src/widgets/Crafting/components/Label.tsx
game/hud/src/widgets/Crafting/components/Minimize.tsx
game/hud/src/widgets/Crafting/components/NameInput.tsx
game/hud/src/widgets/Crafting/components/OutputItems.tsx
game/hud/src/widgets/Crafting/components/PossibleIngredients.tsx
game/hud/src/widgets/Crafting/components/PossibleSlots.tsx
game/hud/src/widgets/Crafting/components/ProgressBar.tsx
game/hud/src/widgets/Crafting/components/QualityInput.tsx
game/hud/src/widgets/Crafting/components/QuantityInput.tsx
game/hud/src/widgets/Crafting/components/RecipeSelect.tsx
game/hud/src/widgets/Crafting/components/RepairItem.tsx
game/hud/src/widgets/Crafting/components/Select.tsx
game/hud/src/widgets/Crafting/components/Tools.tsx
game/hud/src/widgets/Crafting/components/VoxInfo.tsx
game/hud/src/widgets/Crafting/components/VoxMessage.tsx
game/hud/src/widgets/Crafting/styles/index.ts

There are lots of issues with crafting and `css()` from `aphrodite` clashing with the `react-emotion` babel plugin which looks for `css()` from `emotion`.
This renames all occurrences of `css()` to `cssAphrodite()` to remove the issue.

fix crafting css issues

---

game/hud/src/widgets/Settings/components/Key.tsx
game/hud/src/widgets/Settings/panels/KeybindSettings/ClashModal.tsx
game/hud/src/widgets/Settings/panels/KeybindSettings/index.tsx

This PR does three things:
1. Fixes an issue where clearing a keybind isn't cleared, even if applied, until UI is reloaded.  The fix is to clear the keybind immediately, and is still persisted on apply.
2. Some style tweaks
3. Fixes the check for keybind clashes now compares keybind name instead of keybind value (affects binds that use modifier keys shift, alt and ctrl)

Fix clear keybind + fix rebind dialog styles

---

game/hud/src/components/ScenarioResults/components/ScenarioResultsView.tsx
game/hud/src/components/SearchableList/index.tsx

Fixes the things I reported here: https://forums.camelotunchained.com/topic/1522-2-part-testing-on-nuada-prep-saturday-september-8th-2018-italphabeta1/?do=findComment&comment=30783
Some previous changes had moved the close button outside of the close ornament. Changed the position so it is centered in the ornament again.
When the SearchabelList mounted this.scrollRef was undefined. Because of that getVisibleItems returned an empty array, which resulted in an empty list. 
Now, if listHeight exists it doesn't matter if this.scrollRef exists for proper calculations. If listHeight is not provided and this.scrollRef does not exist, we use a placeholder value for the clientHeight. To play it safe I am using the value of a 4k monitor resolution. This way I am rendering more items than I need to, …

Scoreboard / SearchableList improvements

---

game/hud/src/components/HUD/HUDEditor.tsx
game/hud/src/components/HUD/style.ts
game/hud/src/components/HUDDrag/index.scss
game/hud/src/components/HUDDrag/index.tsx
game/hud/src/services/session/layout.ts
game/hud/src/services/session/layoutItems/HUDNav.tsx

This PR fixes some of the issues with the current HUD Editor:
- Changes default HUD Editor position, to a location where the Bug Report button doesn't overlap the scrollbar.
- Fixes the scrollbar not using the CU decorations.
- Greys out items in the HUD Editor list, if a widget is hidden.
- Remove UI Reset button from HUDNav (since it is now in the HUD Editor).
- Lock the UI if any of the fullscreen UI's are opened.
Still to-do:
- Add a button to the HUD Editor that exits edit mode (locks the UI).
- Change style of widget titlebar/border, when widget is hidden.

Various HUD Editor tweaks.

---

game/hud/src/components/Compass/POI/WarbandMembersPoiProvider.tsx

This hopefully fixes an issue with compass warband member POI duplicates.
There is a thread on forums for this: https://forums.camelotunchained.com/topic/1531-compass-shows-group-member-at-two-different-positions/
---
This **Needs** testing in client before merging.

fix compass warband poi

---

game/hud/package.json
yarn.lock

This is an **important** fix to get yarn working again. Is due to security issue with `event-stream` package..
https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

fix security issue for event-stream

---

game/hud/src/widgets/Settings/components/KeybindRow.tsx
library/src/game/clientTasks.ts

This PR fixes an issue whereby the UI crashes when trying to unbind a key.
I also changed `gameTasks` to handle cancelled better.  A cancelled promise will not trigger a resolve, but if the game engine does resolve it when its been cancelled, the promise is rejected with `{ cancelled: true }`.
Also added debugs to `gameTasks` (under game.debug) as cancelling the keybind listener is not working, I suspect its not the promise code, but rather the listener code, in which case the debugs can be removed again.  
Also, when removing a keybind, the code did not attempt to cancel the listener, it should.

Fix UI Crash when unbinding a key

---

game/hud/src/services/session/scenarioQueue.ts
game/hud/src/widgets/ScenarioButton/index.tsx
game/hud/src/widgets/ScenarioJoin/components/Scenario.tsx

Joining/Leaving improvements to feedback and responsiveness.
Attempt to improve the responsiveness of joining/leaving scenario queues. The time taken to join a queue from the point of sending the request to join varies, can be longer than two seconds.  However, the UI waits for the next poll interval to update, which could be 10 seconds away.
When joining/leaving a queue, wait 2 seconds the poll for new data (we effectively bring the poll tick forward to now + 2 seconds).  This allows enough time (in most cases) for the player to have joined the queue, but not too long that it seems to be stuck.
Added immediate feedback to the Find Match / Leave Queue buttons, they now say 'Joining...' or 'Leaving...' whilst the join/leave request is pending.  This gives immediate feedback that it is at …

Scenario Join/Leave improvements
